### si se regstra un shelter
POST http://localhost:3001/register
Content-Type: application/json

{
 "type":"shelter",
 "user":{
  "shelter_name": "BerlinHappy",
   "email":"hector4@hector.com",
   "phone":"123123123",
   "password":"123123123"
  }
}

### si se registra un adoptante
POST http://localhost:3001/register
Content-Type: application/json

{
 "type":"adopter",
 "user":{
   "firstname":"hector2",
   "lastname":"hector2",
   "email":"hector5@hector.com",
   "phone":"123123123",
   "password":"123123123"
  }
}

### Para hacer loguearse
POST  http://localhost:3001/login
Content-Type: application/json

{
  "email":"hector5@hector.com",
  "password":"123123123"
}


### Prueba de token
GET http://localhost:3001/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlY3RvcjNAaGVjdG9yLmNvbSIsInJvbGVJZCI6MSwiaWF0IjoxNzMwMTQ3NzQzLCJleHAiOjE3MzA0MDY5NDN9._6t5FFa6_3juLBSUbHlTv8l8YYj8gZikfX4eFqEWkzc
