### Obtiene todas las mascotas
GET http://localhost:3001/pets

### Obtiene una mascota específica
GET http://localhost:3001/pet/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlY3RvcjNAaGVjdG9yLmNvbSIsInJvbGVJZCI6MSwiaWF0IjoxNzMwMTQ3NzQzLCJleHAiOjE3MzA0MDY5NDN9._6t5FFa6_3juLBSUbHlTv8l8YYj8gZikfX4eFqEWkzc

### Crea una mastcota -- token solo con role de shelter o admin
POST http://localhost:3001/pet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN0cmluZ0BzdHJpbmcuY29tIiwicm9sZUlkIjozLCJpYXQiOjE3MzAxNDgwNDcsImV4cCI6MTczMDQwNzI0N30.5c8Pn_B-SDi-ymtjlRftX4RiBCc66OUksidP_GxQXhQ

{
    "name": "Don vinagre",
    "age" : "3 años",
    "description":"Es un gato muy juguetón, tiene 4 meses de edad", 
    "type":"cat",
    "imageUrl": [
        "https://png.pngtree.com/png-vector/20240205/ourmid/pngtree-cute-little-yellow-cat-png-image_11543557.png",
        "https://st4.depositphotos.com/10614052/40209/i/450/depositphotos_402095220-stock-photo-cute-funny-kitten-color-background.jpg",
        "https://img.freepik.com/fotos-premium/gato-amarillo-pecho-blanco-nariz-rosa_1302549-3268.jpg"
        ]
}

### Edita una mascota --  token solo con role de shelter o admin
PUT http://localhost:3001/pet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlY3RvcjNAaGVjdG9yLmNvbSIsInJvbGVJZCI6MSwiaWF0IjoxNzMwMTQ3NzQzLCJleHAiOjE3MzA0MDY5NDN9._6t5FFa6_3juLBSUbHlTv8l8YYj8gZikfX4eFqEWkzc

{
    "id": 2,
    "infoPet": {
        "type": "cat",
        "name": "vigotes",
        "age": "3 años",
        "description": "Es un gao muy lindo",
        "imageUrl": [
            "https://www.elespectador.com/resizer/KC2rYnJ7xwQ5srRjOCnOHJVE4rw=/arc-anglerfish-arc2-prod-elespectador/public/KHYLDDXDT5BCLBABKRR6LXRLQU.jpg",
            "https://cdn.canal26.com/media/image/2024/07/16/613116.jpg?s=1&a=383004"
            ]
    }
}

### Elimina una Mascota --  token solo con role de shelter o admin
DELETE http://localhost:3001/pet/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlY3RvcjNAaGVjdG9yLmNvbSIsInJvbGVJZCI6MSwiaWF0IjoxNzMwMTQ3NzQzLCJleHAiOjE3MzA0MDY5NDN9._6t5FFa6_3juLBSUbHlTv8l8YYj8gZikfX4eFqEWkzc