### si se regstra un shelter
POST http://localhost:3001/register
Content-Type: application/json

{
 "type":"shelter",
 "shelter":{
  "shelter_name": "BerlinHappy",
   "email":"hector4@hector.com",
   "phone":"123123123",
   "password":"123123123"
  }
}

### si se registra un adoptante
POST http://localhost:3001/register
Content-Type: application/json

{
 "type":"adopter",
 "user":{
   "firstname":"hector2",
   "lastname":"hector2",
   "email":"hector4@hector.com",
   "phone":"123123123",
   "password":"123123123"
  }
}

### Para hacer loguearse
POST  http://localhost:3001/login
Content-Type: application/json

{
  "email":"bh@hector.com",
  "password":"123123123"
}


### Prueba de token
GET http://localhost:3001/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlY3RvckBoZWN0b3IuY29tIiwicm9sZUlkIjoxLCJpYXQiOjE3Mjk2MzMzMzgsImV4cCI6MTcyOTg5MjUzOH0.sqAmvej8s5EkBDRd5QIKQ898GbKKR1u3KXF8OCZ9d_k
